function getAwakeningClient(player, arg)
    local client = {
        {
            ["type"] = "bg",
            ["img"] = "awakening.bmp",
        },
        {
            ["type"] = "close",
            ["x"] = 461,
            ["y"] = 8,
            ["img"] = 243000,
            ["active"] = 243002,
            ["disable"] = 243001,
        },
        {
            ["table"] = "1,0",
            ["width"] = 220,
            ["high"] = 39,
            ["type"] = "lab",
            ["title"] = "#petTitle",
            ["x"] = 90,
            ["y"] = 68,
            ["text"] = "无可选择宠物",
        },
        {
            ["type"] = "btn",
            ["title"] = "pet1Prev",
            ["x"] = 63,
            ["y"] = 65,
            ["img"] = "prev1.bmp",
            ["active"] = "prev2.bmp",
            ["disable"] = "prev3.bmp",
            ["click"] = "awakeningPrev",
        },
        {
            ["type"] = "btn",
            ["title"] = "pet1Next",
            ["x"] = 193,
            ["y"] = 65,
            ["img"] = "next1.bmp",
            ["active"] = "next2.bmp",
            ["disable"] = "next3.bmp",
            ["click"] = "awakeningNext",
        },
        {
            ["table"] = "1,0",
            ["width"] = 220,
            ["high"] = 39,
            ["type"] = "img",
            ["title"] = "#petTitle$Frame",
            ["x"] = 75,
            ["y"] = 89,
            ["img"] = "#petFrame",
        },
        {
            ["table"] = "1,0",
            ["width"] = 220,
            ["high"] = 39,
            ["type"] = "ani",
            ["title"] = "#petTitle$ZImg",
            ["x"] = 0,
            ["y"] = 0,
            ["img"] = 0,
            ["bg"] = "#petTitle$Frame",
        },
        {
            ["table"] = "1,0",
            ["width"] = 220,
            ["high"] = 39,
            ["type"] = "lab",
            ["title"] = "#petTitle$V",
            ["x"] = 78,
            ["y"] = 267,
            ["text"] = "体力: 0",
        },
        {
            ["table"] = "1,0",
            ["width"] = 220,
            ["high"] = 39,
            ["type"] = "lab",
            ["title"] = "#petTitle$S",
            ["x"] = 139,
            ["y"] = 267,
            ["text"] = "力量: 0",
        },
        {
            ["table"] = "1,0",
            ["width"] = 220,
            ["high"] = 39,
            ["type"] = "lab",
            ["title"] = "#petTitle$T",
            ["x"] = 78,
            ["y"] = 282,
            ["text"] = "强度: 0",
        },
        {
            ["table"] = "1,0",
            ["width"] = 220,
            ["high"] = 39,
            ["type"] = "lab",
            ["title"] = "#petTitle$Q",
            ["x"] = 139,
            ["y"] = 282,
            ["text"] = "速度: 0",
        },
        {
            ["table"] = "1,0",
            ["width"] = 220,
            ["high"] = 39,
            ["type"] = "lab",
            ["title"] = "#petTitle$M",
            ["x"] = 78,
            ["y"] = 297,
            ["text"] = "魔法: 0",
        },
        {
            ["table"] = "1,0",
            ["width"] = 220,
            ["high"] = 39,
            ["type"] = "img",
            ["title"] = "#petTitle$Earth",
            ["x"] = 76,
            ["y"] = 207,
            ["img"] = 243150,
        },
        {
            ["table"] = "1,0",
            ["width"] = 220,
            ["high"] = 39,
            ["type"] = "img",
            ["title"] = "#petTitle$Water",
            ["x"] = 76,
            ["y"] = 222,
            ["img"] = 243155,
        },
        {
            ["table"] = "1,0",
            ["width"] = 220,
            ["high"] = 39,
            ["type"] = "img",
            ["title"] = "#petTitle$Fire",
            ["x"] = 76,
            ["y"] = 237,
            ["img"] = 243160,
        },
        {
            ["table"] = "1,0",
            ["width"] = 220,
            ["high"] = 39,
            ["type"] = "img",
            ["title"] = "#petTitle$Wind",
            ["x"] = 76,
            ["y"] = 252,
            ["img"] = 243165,
        },
        {
            ["type"] = "radio",
            ["title"] = "attrType",
            ["x"] = 206,
            ["y"] = 90,
            ["img1"] = 244258,
            ["img2"] = 244257,
            ["layout"] = "0,1",
            ["width"] = 102,
            ["high"] = 22,
            ["texts"] = "地属性觉醒,火属性觉醒,水属性觉醒,风属性觉醒",
            ["values"] = "1,2,3,4",
        },
        {
            ["type"] = "btn",
            ["title"] = "confirm",
            ["x"] = 228,
            ["y"] = 186,
            ["img"] = "y1.bmp",
            ["active"] = "y2.bmp",
            ["disable"] = "y3.bmp",
            ["text"] = "觉醒",
            ["click"] = "awakening",
        },
        {
            ["type"] = "img",
            ["title"] = "item1F",
            ["x"] = 193,
            ["y"] = 237,
            ["img"] = 244284,
        },
        {
            ["type"] = "img",
            ["title"] = "item1D",
            ["x"] = 0,
            ["y"] = 0,
            ["img"] = 0,
        },
        {
            ["type"] = "img",
            ["title"] = "item1Check",
            ["x"] = 201,
            ["y"] = 249,
            ["img"] = "t.bmp",
        },
        {
            ["type"] = "lab",
            ["title"] = "item1Num",
            ["x"] = 203,
            ["y"] = 287,
            ["text"] = "×999",
        },
        {
            ["type"] = "img",
            ["title"] = "item2F",
            ["x"] = 245,
            ["y"] = 237,
            ["img"] = 244284,
        },
        {
            ["type"] = "img",
            ["title"] = "item2D",
            ["x"] = 0,
            ["y"] = 0,
            ["img"] = 0,
        },
        {
            ["type"] = "img",
            ["title"] = "item2Check",
            ["x"] = 253,
            ["y"] = 249,
            ["img"] = "f.bmp",
        },
        {
            ["type"] = "lab",
            ["title"] = "item2Num",
            ["x"] = 255,
            ["y"] = 287,
            ["text"] = "×999",
        }
    }
    Protocol.PowerSend(player:getObj(), "AWAKENING_CLIENT", client)
end

ClientEvent["awakening_client"] = getAwakeningClient