function getPkClient(player, arg)
    local client = {
        {
            ["type"] = "bg",
            ["img"] = "pk.bmp",
        },
        {
            ["type"] = "close",
            ["x"] = 461,
            ["y"] = 8,
            ["img"] = 243000,
            ["active"] = 243002,
            ["disable"] = 243001,
        },
        {
            ["table"] = "1,0",
            ["width"] = 246,
            ["type"] = "lab",
            ["title"] = "#pkTitle$Time",
            ["x"] = 31,
            ["y"] = 90,
            ["text"] = "#pkTime",
        },
        {
            ["table"] = "1,0",
            ["width"] = 246,
            ["type"] = "lab",
            ["title"] = "#pkTitle$Cond",
            ["x"] = 31,
            ["y"] = 117,
            ["text"] = "#pkCond",
        },
        {
            ["table"] = "1,0",
            ["width"] = 246,
            ["type"] = "lab",
            ["title"] = "#pkTitle$Rule",
            ["x"] = 31,
            ["y"] = 145,
            ["text"] = "#pkRule",
        },
        {
            ["table"] = "1,0",
            ["width"] = 246,
            ["type"] = "lab",
            ["title"] = "#pkTitle$Info",
            ["x"] = 31,
            ["y"] = 173,
            ["text"] = "#pkRuleInfo",
        },
        {
            ["table"] = "1,0",
            ["width"] = 246,
            ["type"] = "lab",
            ["title"] = "#pkTitle$Cur",
            ["x"] = 31,
            ["y"] = 199,
            ["text"] = "",
        },
        {
            ["table"] = "1,0",
            ["width"] = 246,
            ["type"] = "lab",
            ["title"] = "#pkTitle$Status",
            ["x"] = 31,
            ["y"] = 227,
            ["text"] = "",
        },
        {
            ["type"] = "btn",
            ["title"] = "singleJoin",
            ["x"] = 96,
            ["y"] = 255,
            ["img"] = "y1.bmp",
            ["active"] = "y2.bmp",
            ["disable"] = "y3.bmp",
            ["text"] = "报名",
            ["click"] = "joinSinglePk",
        },
        {
            ["type"] = "btn",
            ["title"] = "teamJoin",
            ["x"] = 296,
            ["y"] = 255,
            ["img"] = "y1.bmp",
            ["active"] = "y2.bmp",
            ["disable"] = "y3.bmp",
            ["text"] = "报名",
            ["click"] = "joinTeamPk",
        },
        {
            ["type"] = "btn",
            ["title"] = "singleWarp",
            ["x"] = 150,
            ["y"] = 255,
            ["img"] = "y1.bmp",
            ["active"] = "y2.bmp",
            ["disable"] = "y3.bmp",
            ["text"] = "传送",
            ["click"] = "warpPk",
        },
        {
            ["type"] = "btn",
            ["title"] = "teamWarp",
            ["x"] = 348,
            ["y"] = 255,
            ["img"] = "y1.bmp",
            ["active"] = "y2.bmp",
            ["disable"] = "y3.bmp",
            ["text"] = "传送",
            ["click"] = "warpPk",
        }
    }
    Protocol.PowerSend(player:getObj(), "PK_CLIENT", client)
end

ClientEvent["pk_client"] = getPkClient