function getPkClient(player, arg)
    local client = {
        {
            ["type"] = "bg",
            ["img"] = "pk.bmp",
        },
        {
            ["type"] = "close",
            ["x"] = 461,
            ["y"] = 8,
            ["img"] = 243000,
            ["active"] = 243002,
            ["disable"] = 243001,
        },
        {
            ["table"] = "1,0",
            ["width"] = 120,
            ["type"] = "lab",
            ["title"] = "#pkTitle$Time",
            ["x"] = 300,
            ["y"] = 82,
            ["text"] = "#pkTime",
        },
        {
            ["table"] = "1,0",
            ["width"] = 120,
            ["type"] = "lab",
            ["title"] = "#pkTitle$Rule",
            ["x"] = 300,
            ["y"] = 82,
            ["text"] = "#pkRule",
        },
        {
            ["table"] = "1,0",
            ["width"] = 120,
            ["type"] = "lab",
            ["title"] = "#pkTitle$Info",
            ["x"] = 300,
            ["y"] = 82,
            ["text"] = "#pkInfo",
        },
        {
            ["table"] = "1,0",
            ["width"] = 120,
            ["type"] = "lab",
            ["title"] = "#pkTitle$Cur",
            ["x"] = 300,
            ["y"] = 82,
            ["text"] = "--",
        },
        {
            ["table"] = "1,0",
            ["width"] = 120,
            ["type"] = "lab",
            ["title"] = "#pkTitle$Status",
            ["x"] = 300,
            ["y"] = 82,
            ["text"] = "--",
        },
        {
            ["table"] = "1,0",
            ["width"] = 120,
            ["type"] = "btn",
            ["title"] = "#pkTitle$Join",
            ["x"] = 397,
            ["y"] = 143,
            ["img"] = "y1.bmp",
            ["active"] = "y2.bmp",
            ["disable"] = "y3.bmp",
            ["text"] = "报名",
            ["click"] = "#pkFunc",
        },
        {
            ["table"] = "1,0",
            ["width"] = 120,
            ["type"] = "btn",
            ["title"] = "#pkTitle$Warp",
            ["x"] = 397,
            ["y"] = 143,
            ["img"] = "y1.bmp",
            ["active"] = "y2.bmp",
            ["disable"] = "y3.bmp",
            ["text"] = "参赛",
            ["click"] = "warpPk",
        }
    }
    Protocol.PowerSend(player:getObj(), "PK_CLIENT", client)
end

ClientEvent["pk_client"] = getPkClient