function getProficientClient(player, arg)
    local client = {
        {
            ["type"] = "bg",
            ["img"] = "proficient.bmp",
        },
        {
            ["type"] = "close",
            ["x"] = 466,
            ["y"] = 14,
            ["img"] = 243000,
            ["active"] = 243002,
            ["disable"] = 243001,
        },
        {
            ["table"] = "9,1",
            ["high"] = 25,
            ["type"] = "img",
            ["title"] = "#raceTitle$line",
            ["x"] = 106,
            ["y"] = 82,
            ["img"] = "line.bmp",
        },
        {
            ["table"] = "0,1",
            ["high"] = 25,
            ["type"] = "lab",
            ["title"] = "#raceTitle$Z",
            ["x"] = 80,
            ["y"] = 62,
            ["text"] = "#raceTitleVal$:",
        },
        {
            ["table"] = "0,1",
            ["high"] = 25,
            ["type"] = "img",
            ["title"] = "#raceTitle$L",
            ["x"] = 70,
            ["y"] = 57,
            ["img"] = "lab.bmp",
        },
        {
            ["table"] = "0,1",
            ["high"] = 25,
            ["type"] = "lab",
            ["title"] = "#raceTitle$Level",
            ["x"] = 145,
            ["y"] = 62,
            ["text"] = "等级1",
        },
        {
            ["table"] = "0,1",
            ["high"] = 25,
            ["type"] = "img",
            ["title"] = "#raceTitle$AL",
            ["x"] = 137,
            ["y"] = 59,
            ["img"] = "lab1.bmp",
        },
        {
            ["table"] = "0,1",
            ["high"] = 25,
            ["type"] = "lab",
            ["title"] = "#raceTitle$Info",
            ["x"] = 185,
            ["y"] = 62,
            ["text"] = "--",
        },
        {
            ["table"] = "0,1",
            ["high"] = 25,
            ["type"] = "btn",
            ["title"] = "#raceTitle$Up",
            ["x"] = 325,
            ["y"] = 59,
            ["img"] = "b1.bmp",
            ["active"] = "b2.bmp",
            ["disable"] = "b3.bmp",
            ["text"] = "升级",
            ["click"] = "upProficient",
        },
        {
            ["table"] = "0,1",
            ["high"] = 25,
            ["type"] = "btn",
            ["title"] = "#raceTitle$Challenge",
            ["x"] = 379,
            ["y"] = 59,
            ["img"] = "b1.bmp",
            ["active"] = "b2.bmp",
            ["disable"] = "b3.bmp",
            ["text"] = "挑战",
            ["click"] = "raceChallenge",
        }
    }
    Protocol.PowerSend(player:getObj(), "PROFICIENT_CLIENT", client)
end

ClientEvent["proficient_client"] = getProficientClient
